# Site settings
author: Kathleen Kamali
title: A Developer's Grimoire
header-img: img/home-bg.png
email: kathleenkamali@gmail.com
copyright_name: Kathleen Kamali
description: > # this means to ignore newlines until "baseurl:"
  Coding == Witchcraft
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kkamali

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
